# Generated by Django 3.2.5 on 2021-08-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_articlerelationship_commentrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Like', max_length=16)),
                ('com_or_art', models.CharField(default='Article', max_length=16)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentrelationship',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentrelationship',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleRelationship',
        ),
        migrations.DeleteModel(
            name='CommentRelationship',
        ),
    ]
